name: Pack AtosTestSolution

on:
  push:
    paths:
      - contents/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v2
        with:
          solution-file: out/AtosTestSolution.zip
          solution-folder: contents
          solution-type: Both
      - uses: actions/upload-artifact@v3
        with:
          name: packed-solution
          path: out/
